version: "2"

services:
  reverse-proxy:
    build: reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/map

  reverse-proxy-generator:
    build: reverse-proxy-generator
    command: -notify-sighup reverse-proxy -watch /nginx.tmpl /etc/nginx/conf.d/map/generated
    volumes_from:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  jira:
    image: cptactionhank/atlassian-jira-software
    environment:
      VIRTUAL_HOST: jira.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      X_PROXY_NAME: jira.${REVERSE_PROXY_DOMAIN}
      X_PROXY_PORT: ${REVERSE_PROXY_PORT}
      X_PROXY_SCHEME: ${REVERSE_PROXY_PROTO}
    links:
      - db
      - ldap
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence
    environment:
      VIRTUAL_HOST: confluence.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8090
      X_PROXY_NAME: confluence.${REVERSE_PROXY_DOMAIN}
      X_PROXY_PORT: ${REVERSE_PROXY_PORT}
      X_PROXY_SCHEME: ${REVERSE_PROXY_PROTO}
    links:
      - db
      - ldap
    volumes:
      - confluence-data:/var/atlassian/confluence

  gitbucket:
    image: f99aq8ove/gitbucket
    environment:
      VIRTUAL_HOST: git.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      GITBUCKET_DB_URL: jdbc:postgresql://db/gitbucket
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
    links:
      - db
      - ldap
    volumes:
      - gitbucket-data:/gitbucket

  jenkins:
    image: jenkins
    environment:
      VIRTUAL_HOST: jenkins.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
    links:
      - ldap
    volumes:
      - jenkins-data:/var/jenkins_home

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    environment:
      VIRTUAL_HOST: artifactory.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8081
    links:
      - ldap
      - db
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory/data
      - artifactory-conf:/var/opt/jfrog/artifactory/etc

  mattermost:
    image: mattermost/mattermost-prod-app
    environment:
      VIRTUAL_HOST: mattermost.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      MATTERMOST_ENABLE_SSL: ${REVERSE_PROXY_HTTPS}
      DB_HOST: db
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
    links:
      - db
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config

  db:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JIRA_DB_NAME: jira
      JIRA_DB_USER: jira
      JIRA_DB_PASSWORD: jira
      CONFLUENCE_DB_NAME: confluence
      CONFLUENCE_DB_USER: confluence
      CONFLUENCE_DB_PASSWORD: confluence
      GITBUCKET_DB_NAME: gitbucket
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
      MATTERMOST_DB_NAME: mattermost
      MATTERMOST_DB_USER: mattermost
      MATTERMOST_DB_PASSWORD: mattermost
    volumes:
      - db-data:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: example.com
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

volumes:
  jira-data:
    driver: local
  confluence-data:
    driver: local
  gitbucket-data:
    driver: local
  jenkins-data:
    driver: local
  artifactory-data:
    driver: local
  artifactory-conf:
    driver: local
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
  db-data:
    driver: local
  ldap-data:
    driver: local
  ldap-config:
    driver: local
