version: "2"

services:
  jira:
    image: cptactionhank/atlassian-jira-software
    environment:
      X_PATH: /jira
      X_PROXY_NAME: localhost
      X_PROXY_PORT: 80
      X_PROXY_SCHEME: http
    links:
      - db
      - ldap
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence
    environment:
      X_PATH: /confluence
      X_PROXY_NAME: localhost
      X_PROXY_PORT: 80
      X_PROXY_SCHEME: http
    links:
      - db
      - ldap
    volumes:
      - confluence-data:/var/atlassian/confluence

  gitbucket:
    image: f99aq8ove/gitbucket
    environment:
      GITBUCKET_OPTS: --prefix=/gitbucket
      GITBUCKET_DB_URL: jdbc:postgresql://db/gitbucket
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
    links:
      - db
      - ldap
    volumes:
      - gitbucket-data:/gitbucket

  jenkins:
    image: jenkins
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    links:
      - ldap
    volumes:
      - jenkins-data:/var/jenkins_home

  mattermost:
    image: mattermost/mattermost-prod-app
    environment:
      MATTERMOST_ENABLE_SSL: "false"
      DB_HOST: db
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
    links:
      - db
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config

  reverse-proxy:
    build: reverse-proxy
    ports:
      - "80:80"
    links:
      - jenkins
      - gitbucket
      - jira
      - confluence
      - mattermost

  db:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JIRA_DB_NAME: jira
      JIRA_DB_USER: jira
      JIRA_DB_PASSWORD: jira
      CONFLUENCE_DB_NAME: confluence
      CONFLUENCE_DB_USER: confluence
      CONFLUENCE_DB_PASSWORD: confluence
      GITBUCKET_DB_NAME: gitbucket
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
      MATTERMOST_DB_NAME: mattermost
      MATTERMOST_DB_USER: mattermost
      MATTERMOST_DB_PASSWORD: mattermost
    volumes:
      - db-data:/var/lib/postgresql/data

  ldap:
    image: nickstenning/slapd
    environment:
      LDAP_DOMAIN: example.com
      LDAP_ORGANISATION: example.com
      LDAP_ROOTPASS: admin
    volumes:
      - ldap-data:/var/lib/ldap

volumes:
  jira-data:
    driver: local
  confluence-data:
    driver: local
  gitbucket-data:
    driver: local
  jenkins-data:
    driver: local
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
  db-data:
    driver: local
  ldap-data:
    driver: local
